### ISSUE TITLE
Mac OSX -> Cordova problems -> automatic creation of .DS_Store in target folders

### ISSUE THREAD

**Issue by marcelaulenbacher** [mwaylabs/generator-m#123]
Hi.

First of all I'd like to thank you for this more than promising generator.

I stumbled upon a problem using it on Mac OSX Yosemite.
Cordova requires an empty folder, but folders in OSX are never really empty.

There is always a .DS_Store file located in all folders.
It is possible to delete these files, but they are regenerated immediately.

There are options to disable the creation of these files using external software, but as we are speaking about a native OS function I would love to be able to use the generator without modifying base functions of my OS.

Is there any other solution to make this work?

Thank you very much in advance!

**Comment by gruppjo** [comment]
Hi Marcel,
thank you for using our generator and your feedback!

I'm a little surprised since we're using the generator on yosemite extensively and never had any problems with that. How did you create your project folder? We create our folders in the terminal using `mkdir`. Then the `.DS_Store` is not generated until you put in some content into the folder and the generator should run without any problems.

**Comment by marcelaulenbacher** [comment]
Thank you very much for your fast reply. I created the folder in Finder before.

I did as you told me and the generator works well until certain point now.

Now I receive:
angular-animate#1.2.28 app/bower_components/angular-animate
└── angular#1.3.13
npm ERR! Error: EACCES, mkdir '/<a-path>/.npm/opn/0.1.2'
npm ERR!  { [Error: EACCES, mkdir '/<a-path>/.npm/opn/0.1.2']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/<a-path>/.npm/opn/0.1.2' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 14.1.0
npm ERR! command "node" "<a-path>/npm" "install"
npm ERR! cwd /<a-path>
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! path /<a-path>/.npm/opn/0.1.2
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/<a-path>/.npm/opn/0.1.2'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /<a-path>/npm-debug.log
npm ERR! not ok code 0
[16:11:27] Local gulp not found in ~/<a-path>
[16:11:27] Try running: npm install gulp
[16:11:27] Local gulp not found in ~/<a-path>
[16:11:27] Try running: npm install gulp

Thanks again for your friendly help!

**Comment by gruppjo** [comment]
Glad it worked!
Your new error looks like you have an issue with your npm setup. You could try running `npm install` and `bower install` manually to debug. I'm not an npm expert though...
It seems like npm cannot install all dependencies because it doesn't have the proper permissions. It's a little weird, since the generator only installs local packages which should just work fine if you're running the generator with the same user you created the folder with.

What's the path to your project folder that you ran the generator in?

**Comment by marcelaulenbacher** [comment]
Hi again. Sorry for my delay.

My project is located in /Users/MyUser/MyProject

**Comment by gruppjo** [comment]
And you changed in to that folder and then ran `yo m`?

**Comment by marcelaulenbacher** [comment]
Yes I did.

**Comment by marcelaulenbacher** [comment]
Sooooooo... I resolved the issue!

The problem seemed to be located in the npm cache.

**I cleaned the npm cache like this:**
sudo npm cache clean [<path>]

For a full reference on npm cache here some docs:
https://docs.npmjs.com/cli/cache

**Comment by gruppjo** [comment]
Can you please do the following and post all output here:
run the following commands one after another in the terminal anywhere (to check what you have installed)
```shell
npm --version
node --version
npm list -g yo
npm list -g gulp
npm list -g bower
npm list -g generator-m
sass -v
```
run in terminal, in your home folder, again one after another (go there by just running `cd` anywhere in the terminal)
```
pwd
mkdir test && cd $_
yo m --skip-prompts
```
If the problem persists, run the following in the very same directory
```
npm install
```
Please post the commands and the resulting output here.

**Comment by gruppjo** [comment]
Ah, nevermind then!
Thanks for letting us know how you resolved the issue. 
Have fun playing around with the generator and let us know if you're having any problems. 
There will be a new version of the generator available soon. Be sure to check it out!

**Comment by marcelaulenbacher** [comment]
Thank you again! Be sure I'll check it out. :+1:
