### ISSUE TITLE
add prompt for author and description

### ISSUE THREAD

**Issue by MathiasTim** [mwaylabs/generator-m#130]
I would appreciate a prompt at the start for author and description of the project.

This could be added in the package.json and/or in the config.xml.

For now in the config.xml there are the sample informations provided by cordova:

    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>

**Comment by gruppjo** [comment]
related to #135. Unfortunately this can not be done using prompts when running the generator because cordova does not provide a method to set the author and description when creating the project. This can only be done by modifying the `config.xml` after the generator has run. See https://github.com/apache/cordova-lib/blob/master/cordova-lib/src/cordova/create.js#L43
