### ISSUE TITLE
various minor updates

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m#151]
gitter
- ~~https://gitter.im/mwaylabs/generator-m~~
- ~~close https://github.com/mwaylabs/generator-m/pull/154~~
- ~~travis webhooks~~
- ~~github wehooks~~

~~travis.yml notifications~~
- ~~slack~~
- ~~email~~

~~gulpfile~~
- ~~watch-build --no-build~~

~~jscsrc~~
- ~~udpates~~

~~readme~~
- ~~jscs links etc, ... declare as "sensible defaults"~~
- ~~`run ios # works on windows`~~
- ~~rename `127.0.0.1` to `localhost`~~
- ~~gulp config --setBundle (use with care for Android)~~

~~gitignore~~
- ~~www/**~~

~~index.html~~
- ~~title shouldn't be in camelcase~~

~~generator~~
- ~~print version in yosay~~
- ~~more info bitly link~~

**Comment by MathiasTim** [comment]
Just a quick thought I saw when reading the sub-generators part in readme:
Is there a reason why you write:

navigate to http://127.0.0.1:9000/#/ in your browser.
because in other cases you write

navigate to http://localhost:9000 yourself
would be good if this is written the same if it makes no difference

**Comment by gruppjo** [comment]
test
