### ISSUE TITLE
styles not building Invalid option: --sourcemap=none

### ISSUE THREAD

**Issue by ismusidhu** [mwaylabs/generator-m#189]
styles weren't building and upon digging it turned out to be https://github.com/sindresorhus/gulp-ruby-sass/issues/192

There is a simple fix suggested (worked for me) for it which can be committed to even this repo. Though it requires to execute `bundle install` which I'm not sure if it is OK to add.

**Comment by MathiasTim** [comment]
Thanks for your this issue, we will look into it!

**Comment by gruppjo** [comment]
Hi @ismusidhu. This option was initially inserted to avoid a bug in the gulp-ruby-sass package as described here https://github.com/mwaylabs/generator-m/blob/master/app/templates/gulp_tasks/injecting.js#L44. Obviously this workaround causes problems with some versions of Sass.

Which version of Sass are you using? In case you're not sure how to retrieve the version: run `sass -v` in the terminal.

**Comment by ismusidhu** [comment]
I saw the related issue. `libsass` might help. I saw one other generator asking me to choose between these two. I think i was gulp-angular. You night want to have a look at it.

**Comment by ismusidhu** [comment]
Sorry tapped wrong button by mistake.

**Comment by gruppjo** [comment]
We're probably going to go to with the `libsass/nodesass/gulp-sass` stack in the next release. We're not going to offer both because:

1. we want to get rid of the ruby dependency to reduce the number of hurdles and thus make it easier to use for beginners. See https://github.com/mwaylabs/generator-m/issues/3.
2. we won't be able to update to gulp-ruby-sass v1.0.x because their new implementation doesn't go well with our project structure. See https://github.com/mwaylabs/generator-m/issues/199.

I'm gonna close this issue because it's covered in the two I mentioned. Is that ok for you?
