### ISSUE TITLE
Getting errors when updating to latest gulp-ruby-sass

### ISSUE THREAD

**Issue by damiencal** [mwaylabs/generator-m#192]
Upgrading gulp-ruby-sass to latest version (1.0.5) is not backwards compatible with the code below

Injecting.js
```javascript
// build styles to tmp
gulp.task('styles', function () {
  // compile css starting from each module's main.scss
  return gulp.src('app/*/styles/main.scss')
    .pipe($.plumber())
    .pipe($.rubySass({
      style: 'expanded',
      precision: 10,
      'sourcemap=none': true
    }))
    .pipe($.autoprefixer({ browsers: ['last 2 version'], remove: false}))
    .pipe(gulp.dest('.tmp/'));
});
```

**Comment by gruppjo** [comment]
Hi @damiencal, thanks for pointing this out. We haven't updated the npm packages in a couple of weeks,  since it's a lot of maintenance work. But we're planning to do so soon again.

If you're running an npm package with a version that is not supported by the gulpfile (or any other component for that matter) you're very likely to run into issues.

Is there a particular reason you changed the gulp-ruby-sass version in the `package.json` to install the latest version?

**Comment by gruppjo** [comment]
We're probably going to go to with the `libsass/nodesass/gulp-sass` stack in the next release. We're not going to offer both because:

1. we want to get rid of the ruby dependency to reduce the number of hurdles and thus make it easier to use for beginners. See https://github.com/mwaylabs/generator-m/issues/3.
2. we won't be able to update to gulp-ruby-sass v1.0.x because their new implementation doesn't go well with our project structure. See https://github.com/mwaylabs/generator-m/issues/199.

I'm gonna close this issue because it's covered in the two I mentioned. Is that ok for you?
