### ISSUE TITLE
How to generate platform-specific controller, template, etc. in Cordova merges/

### ISSUE THREAD

**Issue by kzurell** [mwaylabs/generator-m#201]
It's unclear where to jump in to create platform-specific overrides in the Cordova merges/ directory. Use generator-m, or do it manually?

The m:controller generator needs an option to restrict to one or more platforms.

**Comment by gruppjo** [comment]
Hi @kzurell, thank you for your suggestion.
Right now we haven't used `merges` in any of our projects because our platform-specific needs are either handled by ionic or we handle them using plugins.
Since we're not familiar with `merges` and don't see cases that could benefit from them, they're not a priority right now.
However we're always eager to learn how others use cordova, so if you want, just provide some cases where it's convenient to use cordova merges and we might reconsider.
