### ISSUE TITLE
Content Security Policy directive

### ISSUE THREAD

**Issue by LunarDevelopment** [mwaylabs/generator-m#203]
Hello, 

I'm getting the below error when gulp watch ing and similar errors when running ionic serve -l 

lines the error relates to: 
```
<script>//<![CDATA[
document.write('<script src="//' + (location.hostname || 'localhost') + ':35729/livereload.js?snipver=1"><\/script>')
//]]></script>
```
Error message in console of latest chrome: 
```
Refused to load the script 'http://localhost:35729/livereload.js?snipver=1' because it violates the following Content Security Policy directive: "default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-inline' 'unsafe-eval'". Note that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.
(anonymous function) @ (index):59
main.js:10 Allo! Allo from your module: main
```

Windows 7, 
latest of all things, e.g. node, npm, yo, generator-m, ionic etc 

Lewis

**Comment by gruppjo** [comment]
Hi @LunarDevelopment. Thank you for reporting this issue. This seems to be a problem with https://github.com/vohof/gulp-livereload and your browser. I did some digging around on goggle/stackoverflow but unfortunately I didn't find anything useful. Maybe you can give it a go yourself?
I guess it also because you are on windows. We're using chrome on mac and this was never a problem?
Also consider creating an issue at the https://github.com/vohof/gulp-livereload repository if this problem exists. Maybe they can help.

I'm closing this issue, because we can't fix it. But please feel free to ask further questions if you get stuck or if my diagnosis was incorrect.
