### ISSUE TITLE
initial module fails in jshintrc

### ISSUE THREAD

**Issue by DrMabuse23** [mwaylabs/generator-m#216]
````js
angular.module('modem', [
  'ionic',
  'ngCordova',
  'ui.router',
  // TODO: load other modules selected during generation
])
`````
too much , see ui.router (there is an additional comma after 'ui-router')

**Comment by gruppjo** [comment]
Hi @DrMabuse23, that's only a problem in older versions of IE. It's only an error in jshint if the `es3` options is enabled which is not the case when generating a project with generator-m, since we're not supporting legacy browsers (just as angular and ionic btw).

See more info here: https://jslinterrors.com/extra-comma

Did any of the gulp tasks report this error, or is it just your IDE? If it's just your IDE you might solve this issue by configuring your IDE to use the `.jshintrc` file that comes with the generated project instead of a different one (which obviously has the `es3` option enabled).
