### ISSUE TITLE
change inject location of default modules

### ISSUE THREAD

**Issue by MathiasTim** [mwaylabs/generator-m#225]
instead injecting it into each module I suppose inject it into the app.js once

**Comment by MathiasTim** [comment]
I hope this is a small improvement and can be done in 1.3.0 @gruppjo ok?

**Comment by gruppjo** [comment]
Yes, the milestone is already applied :)

**Comment by gruppjo** [comment]
I had to revert this. Because it would break karma tests. This is because the karma tests only load the module of the component for which they are created.

It would be possible to add the project's module to every test, but that would make it necessary to read the `.yo-rc.json` in every sub-generator and I'd really rather not do that.

In my opinion it's best just to leave it like this, since there's effectively no down-side of including the dependencies several times, right?

What do you think?
