### ISSUE TITLE
precommit hooks

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m#23]
Provide precommit hooks for:
* jsonlint
* jscs/jshint
* ...

**Comment by gruppjo** [comment]
not really what we want .. http://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks#Client-Side-Hooks

**Comment by MathiasTim** [comment]
maybe worth a look: https://github.com/typicode/husky

**Comment by MathiasTim** [comment]
Just tried 'husky' and it seems quite easy to set up, since we have the linting gulp tasks already.
I used an existing generator-project and installed husky like this:
```npm install husky --save-dev```
Then I added the following lines to the ```package.json```
```
"scripts": {
    "precommit": "gulp linting",
    "prepush": "gulp linting"
 }
```
Then I added an error on purpose. And when I tried to commit, I got the following output:
```
mathiasmaier at Mathiass-MacBook-Pro in ~/Projects/test/gen-test on master [+]
$ git commit -m 'test'
[00:55:37] Using gulpfile ~/Projects/test/gen-test/gulpfile.js
[00:55:37] Starting 'jshint'...
[00:55:37] Starting 'jscs'...
[00:55:37] Starting 'jsonlint'...
[00:55:38] Finished 'jsonlint' after 375 ms
[00:55:38] 'jscs' errored after 821 ms
[00:55:38] Error in plugin 'gulp-jscs'
Message:
    Illegal space after key at main/main.js :
    21 |    })
    22 |      .state('main.list', {
    23 |        url : '/list',
-------------------^
    24 |        views: {
    25 |          'pageContent': {
[00:55:38] Finished 'jshint' after 1.27 s

husky - pre-commit hook failed (add --no-verify to bypass)
```

The problem is: to integrate it into the generator, we have to have a working git-repo.
Maybe we could provide a script, that checks for a repo and installs the commit-hook after the generator is setup, since we cannot create it up first because of cordova.
@gruppjo any ideas? I would provide a pull-request then if we got a resonable solution, I think this feature is easy to build, but powerful to use.

**Comment by gruppjo** [comment]
Great, thanks for bringing this up!

**Comment by gruppjo** [comment]
closing because will be integrated in the course of #231
